- hosts: tag_role_webworker:tag_role_loadbalancer
  user: ubuntu
  sudo: yes

  roles:
   - { role: commonsetup, tags: [ 'common'] }


- hosts: tag_role_webworker
  user: ubuntu
  sudo: yes

  roles:
   - role: php5
   - role: nginx
   - role: webworker


- hosts: tag_role_loadbalancer
  user: ubuntu
  sudo: yes

  roles:
   - role: nginx
   - role: loadbalancer
