# the ubuntu user is specific for Ubuntu AMIs from AWS

- hosts: webstack
  user: ubuntu
  become: yes

  roles:
    - { role: commonsetup, tags: [ 'common'] }
    - role: nginx


- hosts: webworker
  user: ubuntu
  become: yes

  roles:
    - role: php5
    - role: webworker
  



- hosts: loadbalancer
  user: ubuntu
  become: yes

  roles:
    - role: loadbalancer
