- hosts: all
  user: root

  roles:
   - { role: commonsetup, tags: [ 'common'] }


- hosts: webworker
  user: root

  roles:
   - role: php5
   - role: nginx
   - role: webworker


- hosts: loadbalancer
  user: root

  roles:
   - role: nginx
   - role: loadbalancer
