---
  - name: update apt caches
    apt: update_cache=yes
    tags: upgrade

  - name: perform a dist upgrade
    apt: upgrade=dist
    tags: upgrade

  - name: install packages
    action: apt name={{ item }}
    with_items:
     - curl
     - htop
     - bash-completion
