---
  - name: install git
    apt: name=git state=latest

  - name: write nginx config
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: deploy from github repository
    git: repo=https://git@github.com/witscher/ansible-talk-code.git accept_hostkey=true  dest=/opt/app
